import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ProgressBar, ProgressBarProvider } from "react-transition-progress";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-body bg-slate-100">
        <ProgressBarProvider>
          <ProgressBar className="fixed h-1 shadow-lg shadow-indigo-500/20 bg-indigo-500 top-0 z-50" />
          <Header />
          {children}
          <Footer />
        </ProgressBarProvider>
      </body>
    </html>
  );
}
