import type { Metadata } from "next";
import Head from "next/head"; // Import Head

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ProgressBar, ProgressBarProvider } from "react-transition-progress";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-8WMF9P85FP"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-8WMF9P85FP');
            `,
          }}
        />
      </Head>
      <body className="font-body bg-slate-100">
        <ProgressBarProvider>
          <ProgressBar className="fixed h-1 shadow-lg shadow-indigo-500/20 bg-indigo-500 top-0 z-50" />
          <Header />
          {children}
          <Footer />
        </ProgressBarProvider>
      </body>
    </html>
  );
}
